# Generated by Django 4.2.5 on 2023-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('events', '0002_initial'),
        ('users', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
